# Copyright © 2026 John-Helge Gantz. All rights reserved.
#
# Proprietary and confidential.
# Unauthorised use, copying, modification or distribution is prohibited.
# See the LICENSE file at the repository root for complete terms.

"""Configured primary and secondary intelligence sources."""

from __future__ import annotations
from .config import BRIEF_VERSION
from .models import Source

EXECUTIVE_NEWS_RSS = (
    {
        "name": "Cyber Security News",
        "url": "https://cybersecuritynews.com/feed/",
        "base_score": 4,
    },
    {
        "name": "The Hacker News",
        "url": "https://feeds.feedburner.com/TheHackersNews",
        "base_score": 8,
    },
    {
        "name": "SecurityWeek",
        "url": "https://www.securityweek.com/feed/",
        "base_score": 11,
    },
    {
        "name": "BleepingComputer",
        "url": "https://www.bleepingcomputer.com/feed/",
        "base_score": 12,
    },
)

EXECUTIVE_NEWS_HTML = (
    {
        "name": "Reuters Cybersecurity",
        "url": "https://www.reuters.com/technology/cybersecurity/",
        "base_score": 14,
        "selectors": (
            "main a[href*='/technology/']",
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        "include": ("reuters.com",),
        "exclude": (
            "/video/",
            "/pictures/",
            "/graphics/",
            "/legal/",
        ),
    },
    {
        "name": "The Record",
        "url": "https://therecord.media/",
        "base_score": 12,
        "selectors": (
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        "include": ("therecord.media",),
        "exclude": (
            "/tag/",
            "/author/",
            "/category/",
        ),
    },
    {
        "name": "Cybersecurity Dive",
        "url": "https://www.cybersecuritydive.com/",
        "base_score": 10,
        "selectors": (
            "main h2 a[href]",
            "main h3 a[href]",
            "h2 a[href]",
            "h3 a[href]",
        ),
        "include": ("cybersecuritydive.com",),
        "exclude": (
            "/press-release/",
            "/library/",
            "/events/",
            "resources.industrydive.com",
            "sponsored",
        ),
    },
    {
        "name": "Dark Reading",
        "url": "https://www.darkreading.com/",
        "base_score": 8,
        "selectors": (
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        "include": ("darkreading.com",),
        "exclude": (
            "/webinars/",
            "/resources/",
            "/whitepapers/",
            "sponsored",
            "partner",
        ),
    },
    {
        "name": "BankInfoSecurity",
        "url": "https://www.bankinfosecurity.com/",
        "base_score": 9,
        "selectors": (
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        "include": ("bankinfosecurity.com",),
        "exclude": (
            "/webinars/",
            "/whitepapers/",
            "/events/",
            "/interviews/",
        ),
    },
    {
        "name": "SC World",
        "url": "https://www.scworld.com/",
        "base_score": 6,
        "selectors": (
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        "include": ("scworld.com",),
        "exclude": (
            "/resource/",
            "/events/",
            "/sponsored/",
        ),
    },
    {
        "name": "Industrial Cyber",
        "url": "https://industrialcyber.co/",
        "base_score": 12,
        "selectors": (
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        "include": ("industrialcyber.co",),
        "exclude": (
            "/events/",
            "/webinars/",
            "/sponsored/",
        ),
    },
)

EXECUTIVE_NEWS_SOURCE_LIMITS = {
    "Reuters Cybersecurity": 2,
    "SecurityWeek": 2,
    "BleepingComputer": 2,
    "The Record": 2,
    "The Hacker News": 2,
    "Cybersecurity Dive": 1,
    "Cyber Security News": 1,
    "Dark Reading": 1,
    "BankInfoSecurity": 1,
    "SC World": 1,
    "Industrial Cyber": 2,
}

RSS_SOURCES = (
    Source(
        name="Microsoft Security Blog",
        vendor="Microsoft",
        url="https://www.microsoft.com/en-us/security/blog/feed/",
        source_type="rss",
        base_score=30,
        section="Microsoft",
    ),
    Source(
        name="AWS Security Blog",
        vendor="AWS",
        url="https://aws.amazon.com/blogs/security/feed/",
        source_type="rss",
        base_score=18,
        section="Cloud and Identity",
    ),
    Source(
        name="Palo Alto Unit 42",
        vendor="Palo Alto Networks",
        url="https://unit42.paloaltonetworks.com/feed/",
        source_type="rss",
        base_score=28,
        section="Threat Intelligence",
    ),
    Source(
        name="Google Project Zero",
        vendor="Google",
        url=(
            "https://googleprojectzero.blogspot.com/feeds/posts/"
            "default?alt=rss"
        ),
        source_type="rss",
        base_score=24,
        section="Vulnerability Research",
    ),

    Source(
        name="Google Security Blog",
        vendor="Google",
        url=(
            "https://security.googleblog.com/feeds/posts/"
            "default?alt=rss"
        ),
        source_type="rss",
        base_score=26,
        section="Vulnerability Research",
    ),
    Source(
        name="CrowdStrike Blog",
        vendor="CrowdStrike",
        url="https://www.crowdstrike.com/en-us/blog/feed/",
        source_type="rss",
        base_score=24,
        section="Threat Intelligence",
    ),
    Source(
        name="The DFIR Report",
        vendor="The DFIR Report",
        url="https://thedfirreport.com/feed/",
        source_type="rss",
        base_score=30,
        section="SOC and Detection Engineering",
    ),
    Source(
        name="SigmaHQ Releases",
        vendor="SigmaHQ",
        url="https://github.com/SigmaHQ/sigma/releases.atom",
        source_type="rss",
        base_score=22,
        section="SOC and Detection Engineering",
    ),
)

HTML_SOURCES = (
    Source(
        name="Cisco Talos",
        vendor="Cisco",
        url="https://blog.talosintelligence.com/",
        source_type="html",
        base_score=28,
        section="Threat Intelligence",
        selectors=(
            "h2 a[href]",
            "h3 a[href]",
        ),
        include_patterns=("blog.talosintelligence.com",),
        exclude_patterns=(
            "/search/",
            "/p/",
            "/feeds/",
            "threat-source-newsletter",
        ),
        max_candidates=30,
    ),
    Source(
        name="Fortinet PSIRT",
        vendor="Fortinet",
        url="https://www.fortiguard.com/psirt",
        source_type="html",
        base_score=40,
        section="Fortinet",
        selectors=(
            "a[href*='/psirt/FG-IR-']",
            "a[href*='/psirt/fg-ir-']",
        ),
        include_patterns=("/psirt/",),
        max_candidates=40,
    ),
    Source(
        name="FortiGuard Labs Threat Research",
        vendor="Fortinet",
        url="https://www.fortinet.com/blog/threat-research",
        source_type="html",
        base_score=32,
        section="Fortinet",
        selectors=(
            "h2 a[href]",
            "h3 a[href]",
        ),
        include_patterns=("/blog/threat-research/",),
        exclude_patterns=(
            "/blog/threat-research$",
            "customer-success",
            "webinar",
        ),
        max_candidates=35,
    ),
    Source(
        name="HPE Security Bulletin Library",
        vendor="HPE",
        url=(
            "https://support.hpe.com/connect/s/"
            "securitybulletinlibrary?language=en_US"
        ),
        source_type="html",
        base_score=38,
        section="HPE",
        selectors=(
            "a[href*='docDisplay'][href*='hpesb']",
            "a[href*='docDisplay'][href*='HPESB']",
            "article a[href]",
            "table a[href]",
        ),
        include_patterns=("hpesb",),
        max_candidates=45,
    ),
    Source(
        name="Apple Security Releases",
        vendor="Apple",
        url="https://support.apple.com/en-us/100100",
        source_type="html",
        base_score=30,
        section="Other Vendor Advisories",
        selectors=(
            "table a[href]",
            "h2 a[href]",
            "h3 a[href]",
        ),
        include_patterns=("support.apple.com",),
        exclude_patterns=(
            "/guide/",
            "/contact",
            "/en-us/HT",
        ),
        max_candidates=35,
    ),
    Source(
        name="Okta Security",
        vendor="Okta",
        url="https://sec.okta.com/articles/",
        source_type="html",
        base_score=30,
        section="Cloud and Identity",
        selectors=(
            "h2 a[href]",
            "h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("sec.okta.com/articles/",),
        exclude_patterns=("/articles/$",),
        max_candidates=25,
    ),
    Source(
        name="ENISA News",
        vendor="ENISA",
        url="https://www.enisa.europa.eu/news",
        source_type="html",
        base_score=32,
        section="Compliance",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("enisa.europa.eu",),
        exclude_patterns=(
            "/events/",
            "/about-enisa/",
            "/topics/",
            "/publications/",
            "vacancies",
        ),
        max_candidates=45,
    ),
    Source(
        name="NIST CSRC News",
        vendor="NIST",
        url="https://csrc.nist.gov/News",
        source_type="html",
        base_score=30,
        section="Standards",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
            ".news-item a[href]",
        ),
        include_patterns=("csrc.nist.gov",),
        exclude_patterns=(
            "/events/",
            "/projects/",
            "/publications/",
            "#",
        ),
        max_candidates=40,
    ),
    Source(
        name="PCI Security Standards Council",
        vendor="PCI SSC",
        url="https://blog.pcisecuritystandards.org/",
        source_type="html",
        base_score=30,
        section="Compliance",
        selectors=(
            "article h2 a[href]",
            "article h3 a[href]",
            "h2 a[href]",
            "h3 a[href]",
        ),
        include_patterns=("pcisecuritystandards.org",),
        exclude_patterns=(
            "/tag/",
            "/author/",
            "/category/",
        ),
        max_candidates=35,
    ),
    Source(
        name="ISACA News and Trends",
        vendor="ISACA",
        url="https://www.isaca.org/resources/news-and-trends",
        source_type="html",
        base_score=24,
        section="GRC",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("isaca.org",),
        exclude_patterns=(
            "/credentialing/",
            "/training-and-events/",
            "/membership/",
            "/career-centre/",
        ),
        max_candidates=35,
    ),

    Source(
        name="NSM Updates",
        vendor="NSM Norway",
        url="https://nsm.no/aktuelt/",
        source_type="html",
        base_score=40,
        section="Norwegian Security Governance",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
            "main a[href]",
        ),
        include_patterns=("nsm.no/",),
        exclude_patterns=(
            "#",
            "kontakt",
            "personvern",
            "tilgjengelighet",
        ),
        max_candidates=50,
        locale="no",
    ),
    Source(
        name="ISO News",
        vendor="ISO",
        url="https://www.iso.org/news.html",
        source_type="html",
        base_score=35,
        section="Standards",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
            ".news-item a[href]",
        ),
        include_patterns=("iso.org",),
        exclude_patterns=(
            "/store.html",
            "/members.html",
            "/events.html",
            "privacy",
            "terms",
        ),
        max_candidates=55,
        topic_keywords=(
            "iso/iec 27001",
            "iso 27001",
            "iso 50001",
            "iso 9001",
            "iso 14001",
            "iso/iec 330",
            "iso 33000",
            "management system standard",
            "information security management",
            "quality management",
            "environmental management",
            "energy management",
            "process assessment",
        ),
    ),
    Source(
        name="Elastic Security Labs",
        vendor="Elastic",
        url="https://www.elastic.co/security-labs",
        source_type="html",
        base_score=28,
        section="SOC and Detection Engineering",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("elastic.co/security-labs",),
        exclude_patterns=(
            "/about/",
            "/careers/",
            "/contact/",
        ),
        max_candidates=35,
    ),
    Source(
        name="Splunk Security Blog",
        vendor="Splunk",
        url="https://www.splunk.com/en_us/blog/security.html",
        source_type="html",
        base_score=25,
        section="SOC and Detection Engineering",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("splunk.com",),
        exclude_patterns=(
            "/events/",
            "/conf",
            "/customer-stories/",
            "webinar",
        ),
        max_candidates=35,
    ),
    Source(
        name="CISA ICS Advisories",
        vendor="CISA",
        url="https://www.cisa.gov/news-events/ics-advisories",
        source_type="html",
        base_score=42,
        section="OT, Energy and Oil & Gas",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
            "main a[href*='/news-events/ics-advisories/']",
        ),
        include_patterns=("/news-events/ics-advisories/",),
        exclude_patterns=(
            "/ics-advisories$",
            "#",
        ),
        max_candidates=60,
    ),
    Source(
        name="Dragos",
        vendor="Dragos",
        url="https://www.dragos.com/blog/",
        source_type="html",
        base_score=34,
        section="OT, Energy and Oil & Gas",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("dragos.com/blog",),
        exclude_patterns=(
            "/events/",
            "/resources/",
            "webinar",
        ),
        max_candidates=40,
    ),
    Source(
        name="Claroty Team82",
        vendor="Claroty",
        url="https://claroty.com/team82/research",
        source_type="html",
        base_score=34,
        section="OT, Energy and Oil & Gas",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("claroty.com",),
        exclude_patterns=(
            "/events/",
            "/webinars/",
            "/resources/",
        ),
        max_candidates=40,
    ),
    Source(
        name="Nozomi Networks Labs",
        vendor="Nozomi Networks",
        url="https://www.nozominetworks.com/blog",
        source_type="html",
        base_score=32,
        section="OT, Energy and Oil & Gas",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
        ),
        include_patterns=("nozominetworks.com/blog",),
        exclude_patterns=(
            "/events/",
            "/webinars/",
            "/resources/",
        ),
        max_candidates=40,
    ),
    Source(
        name="FBI Cyber News",
        vendor="FBI",
        url="https://www.fbi.gov/investigate/cyber/news",
        source_type="html",
        base_score=30,
        section="Dark Web and Criminal Ecosystem",
        selectors=(
            "main h2 a[href]",
            "main h3 a[href]",
            "article a[href]",
            "main a[href*='/news/press-releases/']",
            "main a[href*='/news/stories/']",
        ),
        include_patterns=("fbi.gov/",),
        exclude_patterns=(
            "/wanted/",
            "/contact-us/",
            "/services/",
            "/history/",
        ),
        topic_keywords=(
            "ransomware",
            "cybercrime",
            "cybercriminal",
            "dark web",
            "stolen access",
            "selling access",
            "initial access",
            "infostealer",
            "stealer",
            "phishing",
            "malware",
            "botnet",
            "extortion",
            "data breach",
            "hacking group",
            "marketplace",
            "stolen credentials",
            "access token",
            "sanction",
            "takedown",
        ),
        max_candidates=60,
    ),
    Source(
        name="NSM Security Warnings",
        vendor="NSM Norway",
        url=(
            "https://nsm.no/fagomrader/digital-sikkerhet/"
            "nasjonalt-cybersikkerhetssenter/varsler-fra-nsm/"
        ),
        source_type="html",
        base_score=38,
        section="Nordic Impact",
        selectors=(
            "main a[href]",
            "article a[href]",
            "h2 a[href]",
            "h3 a[href]",
        ),
        include_patterns=("nsm.no/",),
        exclude_patterns=(
            "#",
            "/2026/",
            "/2025/",
            "/2024/",
            "/2023/",
            "/2022/",
            "/2021/",
            "/2020/",
            "/2019/",
            "/2018/",
            "kontakt",
            "personvern",
            "tilgjengelighet",
        ),
        max_candidates=45,
        locale="no",
    ),
)
